export const LOG_IN_REQUEST = "LOG_IN_REQUEST";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_ERROR = "LOG_IN_ERROR";
export const LOG_OUT = "LOG_OUT";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

/******USER ACTIONS**********/
export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_ERROR = "GET_USER_PROFILE_ERROR";


/******NAVIGATION ACTIONS************ */
export const COLLAPSE_MENU = "COLLAPSE_MENU";
export const COLLAPSE_TOGGLE = "COLLAPSE_TOGGLE";
export const FULL_SCREEN = "FULL_SCREEN";
export const FULL_SCREEN_EXIT = "FULL_SCREEN_EXIT";
export const CHANGE_LAYOUT = "CHANGE_LAYOUT";
export const NAV_CONTENT_LEAVE = "NAV_CONTENT_LEAVE";
export const NAV_COLLAPSE_LEAVE = "NAV_COLLAPSE_LEAVE";
export const SHOW_MODAL = "SHOW_MODAL";
export const EXIT_MODAL = "EXIT_MODAL";

/******PRODUCT ACTIONS************ */
 export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
 export const  DELETE_PRODUCT_ERROR ="DELETE_PRODUCT_ERROR";
 export const ADD_PRODUCT_SUCCESS ="ADD_PRODUCT_SUCCESS";
 export const ADD_PRODUCT_ERROR ="ADD_PRODUCT_ERROR";
 export const GET_ALL_PRODUCTS_SUCCESS="GET_ALL_PRODUCTS_SUCCESS";
 export const GET_ALL_PRODUCTS_ERROR="GET_ALL_PRODUCTS_ERROR";
 export const UPDATE_PRODUCT_SUCCESS="UPDATE_PRODUCT_SUCCESS";
 export const UPDATE_PRODUCT_ERROR="UPDATE_PRODUCT_ERROR"
